meta:
  library: energydata
  basename: bsee
basename: bsee

production:
  flag: True
  analysis: False


settings:
  save_csv: True
  url: https://www.data.bsee.gov/Production/ProductionData/Default.aspx
  output_dir: None
  label: None
  lease_number: None
  Duration:
    from : 01/1999
    to : 12/2024
  form_data:
    first_request:
      ASPxFormLayout1$ASPxTextBoxLN: 
      ASPxFormLayout1$ASPxTextBoxDF: 
      ASPxFormLayout1$ASPxTextBoxDT: 
      ASPxFormLayout1$ASPxButtonSubmitQ: "Submit Query"

    second_request:
      ASPxFormLayout1$ASPxTextBoxLN: 
      __EVENTTARGET: "ASPxFormLayout2$btnCsvExport"
      __EVENTARGUMENT: "Click"


default:
  log_level: DEBUG
  config:
    overwrite:
      output: True
    cfg_sensitivities: False
