meta:
  library: energydata
  basename: bsee
basename: bsee

production:
  flag: True
  analysis: False

settings:
  save_csv: True
  url: https://https://www.data.bsee.gov/Main/OGOR-A.aspx
  output_dir: None
  input:
    - a12
  source:
    - ogor-A zip files
