name: energydata
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - pip
  - pip:
      # - -r file:requirements.txt # source pip specific requirements
      - beautifulsoup4
      - attrs
      - bs4
      - certifi
      - cffi
      - h11
      - idna
      - numpy
      - outcome
      - pandas
      - pycparser
      - PySocks
      - python-dateutil
      - pytz
      - selenium
      - six
      - sniffio
      - sortedcontainers
      - soupsieve
      - trio
      - trio-websocket
      - typing_extensions
      - tzdata
      - urllib3
      - wsproto
      - pyyaml
      - assetutilities
      - pytest
      - deepdiff
      - requests
